### ISSUE TITLE
Facebook Video Error "'v' is not recognized as an internal or external command,"

### ISSUE THREAD

**Issue by appysrinath** [streamlink/windows-builds#3]
### Build flavor

Portable - Python 3.8 - x86_64 (64 bit)

### Build version

5.2.1-1

### Description

C:\Program Files (x86)\Streamlink\bin>streamlink.exe https://www.facebook.com/watch/live/?ref=watch_permalink&v=722966112666211 best
error: No plugin can handle URL: https://www.facebook.com/watch/live/?ref=watch_permalink
'v' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files (x86)\Streamlink\bin>streamlink.exe https://www.facebook.com/V6News.tv/videos/722966112666211 best
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/V6News.tv/videos/722966112666211
error: No playable streams found on this URL: https://www.facebook.com/V6News.tv/videos/722966112666211

**Comment by bastimeyer** [comment]
Neither a Streamlink nor a Streamlink Windows builds issue.

You need to quote your input string or escape special characters like `&`, so that `&` doesn't get interpreted as a command separator by your Windows `cmd.exe` shell.

Explained in more detail here:
https://github.com/streamlink/streamlink/discussions/3899#discussioncomment-1128235
